research_task:
  description: >
    Our prompt isn't working well due to the following feedback: {feedback}.
    Help us find the right techniques to improve it.
  expected_output: >
    A list of 5 tips on how to improve a prompt.
  agent: researcher

improve_prompt_task:
  description: >
    You are given the following prompt: {prompt}.
    We evaluated it and got the following score: {score}.
    With the following feedback: {feedback}.
    Update the prompt to improve the quality of the response.
    Make sure to follow the tips that were provided.
    The updated prompt you provide will be sent as-is,
    so assume no extra context from past conversations is available.
    Make sure not to overfit to the specific feedback.
    Do not change the templated variables marked with {}.
  expected_output: >
    A templated string representing the updated prompt.
  agent: prompt_engineer
  context:
    - research_task
